#!/bin/sh -x

trap 'onerr' ERR

e=`echo hi | src/encrypt sss '{"t": 1, "pins": {"test": [{"fail": false}, {"fail": false}]}}'`
d=`echo $e | src/decrypt`
test "$d" == "hi"

e=`echo hi | src/encrypt sss '{"t": 1, "pins": {"test": [{"fail": true}, {"fail": false}]}}'`
d=`echo $e | src/decrypt`
test "$d" == "hi"

e=`echo hi | src/encrypt sss '{"t": 1, "pins": {"test": [{"fail": false}, {"fail": true}]}}'`
d=`echo $e | src/decrypt`
test "$d" == "hi"

e=`echo hi | src/encrypt sss '{"t": 1, "pins": {"test": [{"fail": true}, {"fail": true}]}}'`
! echo $e | src/decrypt

e=`echo hi | src/encrypt sss '{"t": 2, "pins": {"test": [{"fail": false}, {"fail": false}]}}'`
d=`echo $e | src/decrypt`
test "$d" == "hi"

e=`echo hi | src/encrypt sss '{"t": 2, "pins": {"test": [{"fail": true}, {"fail": false}]}}'`
! echo $e | src/decrypt

e=`echo hi | src/encrypt sss '{"t": 2, "pins": {"test": [{"fail": false}, {"fail": true}]}}'`
! echo $e | src/decrypt

e=`echo hi | src/encrypt sss '{"t": 2, "pins": {"test": [{"fail": true}, {"fail": true}]}}'`
! echo $e | src/decrypt

