#!/bin/sh -x

trap 'exit' ERR

PORT=`shuf -i 1024-65535 -n 1`

python tests/httpd.py $PORT &
export PID=$!
sleep 1

function onerr() {
    kill -9 $PID
    ! wait $PID
    exit 1
}

trap 'onerr' ERR

e=`echo hi | cmd/encrypt http "{\"url\": \"http://localhost:${PORT}/foo\"}"`
d=`echo $e | cmd/decrypt`
test "$d" == "hi"

kill -9 $PID
! wait $PID

trap 'exit' ERR

! echo $e | cmd/decrypt
