#!/bin/sh -ex

e=`echo hi | cmd/encrypt sss '{"t": 1, "pins": {"test": [{"fail": false}, {"fail": false}]}}'`
d=`echo $e | cmd/decrypt`
test "$d" == "hi"

e=`echo hi | cmd/encrypt sss '{"t": 1, "pins": {"test": [{"fail": true}, {"fail": false}]}}'`
d=`echo $e | cmd/decrypt`
test "$d" == "hi"

e=`echo hi | cmd/encrypt sss '{"t": 1, "pins": {"test": [{"fail": false}, {"fail": true}]}}'`
d=`echo $e | cmd/decrypt`
test "$d" == "hi"

e=`echo hi | cmd/encrypt sss '{"t": 1, "pins": {"test": [{"fail": true}, {"fail": true}]}}'`
! echo $e | cmd/decrypt

e=`echo hi | cmd/encrypt sss '{"t": 2, "pins": {"test": [{"fail": false}, {"fail": false}]}}'`
d=`echo $e | cmd/decrypt`
test "$d" == "hi"

e=`echo hi | cmd/encrypt sss '{"t": 2, "pins": {"test": [{"fail": true}, {"fail": false}]}}'`
! echo $e | cmd/decrypt

e=`echo hi | cmd/encrypt sss '{"t": 2, "pins": {"test": [{"fail": false}, {"fail": true}]}}'`
! echo $e | cmd/decrypt

e=`echo hi | cmd/encrypt sss '{"t": 2, "pins": {"test": [{"fail": true}, {"fail": true}]}}'`
! echo $e | cmd/decrypt

