#!/bin/bash -ex

export device=$1

bits=`cryptsetup luksDump $device | sed -r -n 's|MK bits:[ \t]*([0-9]+)|\1|p'`
bytes=$(($bits / 8))
new=`od -An -N $bytes -t x8 /dev/urandom`
new=`echo $new | sed 's| ||g'`
cmd=`dirname $0`/clevis-pin-$2
jwe=`echo -n $new | $cmd encrypt "$3"`

if ! luksmeta test -d $device; then
    luksmeta init -d $device
fi

export slot=`echo -n $jwe | luksmeta save -d $device -u cb6e8904-81ff-40da-a84a-07ab9ab5715e`

function onerr() {
    luksmeta wipe -f -d $device -u cb6e8904-81ff-40da-a84a-07ab9ab5715e -s $slot
}

trap 'onerr' ERR

read -s -p "Enter existing LUKS password: " old
echo

echo -e "$old\n$new" | cryptsetup luksAddKey -S $slot $device
